# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chatapp_pb2 as chatapp__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chatapp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """all the RPCs for the messaging app are defined under ChatService.

    these are all the different things that the app needs to be able to do:
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/chat.ChatService/Login',
                request_serializer=chatapp__pb2.LoginRequest.SerializeToString,
                response_deserializer=chatapp__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/chat.ChatService/SendMessage',
                request_serializer=chatapp__pb2.MessageRequest.SerializeToString,
                response_deserializer=chatapp__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ReceiveMessages = channel.unary_stream(
                '/chat.ChatService/ReceiveMessages',
                request_serializer=chatapp__pb2.ReceiveMessagesRequest.SerializeToString,
                response_deserializer=chatapp__pb2.ChatMessageResponse.FromString,
                _registered_method=True)
        self.GetPendingMessages = channel.unary_unary(
                '/chat.ChatService/GetPendingMessages',
                request_serializer=chatapp__pb2.PendingMessagesRequest.SerializeToString,
                response_deserializer=chatapp__pb2.PendingMessagesResponse.FromString,
                _registered_method=True)
        self.MoreMessages = channel.unary_unary(
                '/chat.ChatService/MoreMessages',
                request_serializer=chatapp__pb2.MoreMessagesRequest.SerializeToString,
                response_deserializer=chatapp__pb2.MoreMessagesResponse.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/chat.ChatService/DeleteMessage',
                request_serializer=chatapp__pb2.DeleteMessageRequest.SerializeToString,
                response_deserializer=chatapp__pb2.DeleteMessageResponse.FromString,
                _registered_method=True)
        self.DeleteAccount = channel.unary_unary(
                '/chat.ChatService/DeleteAccount',
                request_serializer=chatapp__pb2.DeleteAccountRequest.SerializeToString,
                response_deserializer=chatapp__pb2.DeleteAccountResponse.FromString,
                _registered_method=True)
        self.ListAccounts = channel.unary_unary(
                '/chat.ChatService/ListAccounts',
                request_serializer=chatapp__pb2.ListAccountsRequest.SerializeToString,
                response_deserializer=chatapp__pb2.ListAccountsResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """all the RPCs for the messaging app are defined under ChatService.

    these are all the different things that the app needs to be able to do:
    """

    def Login(self, request, context):
        """login or account creation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """send a message from one user to another
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request, context):
        """RPC to receive messages as a stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingMessages(self, request, context):
        """get the most recent pending messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoreMessages(self, request, context):
        """retrieves additional pending messages in chunks of 10 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """deletes a message 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """deletes an account after confirming 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccounts(self, request, context):
        """lists all registered accounts, maybe filter by a wildcard if the user prompts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=chatapp__pb2.LoginRequest.FromString,
                    response_serializer=chatapp__pb2.LoginResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chatapp__pb2.MessageRequest.FromString,
                    response_serializer=chatapp__pb2.MessageResponse.SerializeToString,
            ),
            'ReceiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=chatapp__pb2.ReceiveMessagesRequest.FromString,
                    response_serializer=chatapp__pb2.ChatMessageResponse.SerializeToString,
            ),
            'GetPendingMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingMessages,
                    request_deserializer=chatapp__pb2.PendingMessagesRequest.FromString,
                    response_serializer=chatapp__pb2.PendingMessagesResponse.SerializeToString,
            ),
            'MoreMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.MoreMessages,
                    request_deserializer=chatapp__pb2.MoreMessagesRequest.FromString,
                    response_serializer=chatapp__pb2.MoreMessagesResponse.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=chatapp__pb2.DeleteMessageRequest.FromString,
                    response_serializer=chatapp__pb2.DeleteMessageResponse.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=chatapp__pb2.DeleteAccountRequest.FromString,
                    response_serializer=chatapp__pb2.DeleteAccountResponse.SerializeToString,
            ),
            'ListAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccounts,
                    request_deserializer=chatapp__pb2.ListAccountsRequest.FromString,
                    response_serializer=chatapp__pb2.ListAccountsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """all the RPCs for the messaging app are defined under ChatService.

    these are all the different things that the app needs to be able to do:
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/Login',
            chatapp__pb2.LoginRequest.SerializeToString,
            chatapp__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/SendMessage',
            chatapp__pb2.MessageRequest.SerializeToString,
            chatapp__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.ChatService/ReceiveMessages',
            chatapp__pb2.ReceiveMessagesRequest.SerializeToString,
            chatapp__pb2.ChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetPendingMessages',
            chatapp__pb2.PendingMessagesRequest.SerializeToString,
            chatapp__pb2.PendingMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoreMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/MoreMessages',
            chatapp__pb2.MoreMessagesRequest.SerializeToString,
            chatapp__pb2.MoreMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/DeleteMessage',
            chatapp__pb2.DeleteMessageRequest.SerializeToString,
            chatapp__pb2.DeleteMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/DeleteAccount',
            chatapp__pb2.DeleteAccountRequest.SerializeToString,
            chatapp__pb2.DeleteAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/ListAccounts',
            chatapp__pb2.ListAccountsRequest.SerializeToString,
            chatapp__pb2.ListAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RaftServiceStub(object):
    """-----------------------
    Raft Service Definitions
    -----------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/chat.RaftService/RequestVote',
                request_serializer=chatapp__pb2.RequestVoteRequest.SerializeToString,
                response_deserializer=chatapp__pb2.RequestVoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/chat.RaftService/AppendEntries',
                request_serializer=chatapp__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=chatapp__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/chat.RaftService/Ping',
                request_serializer=chatapp__pb2.PingRequest.SerializeToString,
                response_deserializer=chatapp__pb2.PingResponse.FromString,
                _registered_method=True)
        self.AddServer = channel.unary_unary(
                '/chat.RaftService/AddServer',
                request_serializer=chatapp__pb2.AddServerRequest.SerializeToString,
                response_deserializer=chatapp__pb2.AddServerResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/chat.RaftService/HealthCheck',
                request_serializer=chatapp__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=chatapp__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RaftServiceServicer(object):
    """-----------------------
    Raft Service Definitions
    -----------------------

    """

    def RequestVote(self, request, context):
        """RPC for requesting votes during leader election.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """RPC for heartbeats and log replication.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """RPC for pings 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddServer(self, request, context):
        """RPC for adding a new server to the cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """RPC for checking cluster health 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=chatapp__pb2.RequestVoteRequest.FromString,
                    response_serializer=chatapp__pb2.RequestVoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=chatapp__pb2.AppendEntriesRequest.FromString,
                    response_serializer=chatapp__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=chatapp__pb2.PingRequest.FromString,
                    response_serializer=chatapp__pb2.PingResponse.SerializeToString,
            ),
            'AddServer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddServer,
                    request_deserializer=chatapp__pb2.AddServerRequest.FromString,
                    response_serializer=chatapp__pb2.AddServerResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=chatapp__pb2.HealthCheckRequest.FromString,
                    response_serializer=chatapp__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.RaftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """-----------------------
    Raft Service Definitions
    -----------------------

    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.RaftService/RequestVote',
            chatapp__pb2.RequestVoteRequest.SerializeToString,
            chatapp__pb2.RequestVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.RaftService/AppendEntries',
            chatapp__pb2.AppendEntriesRequest.SerializeToString,
            chatapp__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.RaftService/Ping',
            chatapp__pb2.PingRequest.SerializeToString,
            chatapp__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.RaftService/AddServer',
            chatapp__pb2.AddServerRequest.SerializeToString,
            chatapp__pb2.AddServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.RaftService/HealthCheck',
            chatapp__pb2.HealthCheckRequest.SerializeToString,
            chatapp__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
