syntax = "proto3";

package timesystem;

//all the RPCs for the messaging app are defined under ChatService.

service CommunicationService {
  //these are all the different things that the app needs to be able to do:

  //send a message from one user to another
  rpc SendMessage (MessageRequest) returns (MessageResponse);

  // RPC to receive messages as a stream.
  rpc ReceiveMessages (ReceiveMessagesRequest) returns (stream ChatMessageResponse);
}


// ----------- Message Definitions -----------


//request for sending a message
message MessageRequest {
  string sender = 1;
  string recipient = 2;
  string message = 3;
}

//response for sending a message
message MessageResponse {
  bool delivered = 1;
  string message = 2;
}

//messages that are forwarded over by the server 
message ChatMessage {
  string sender = 1;
  string recipient = 2;
  string message = 3;
}

message SendMessageRequest {
  string sender = 1;
  string recipient = 2;
  string message = 3;
}

message SendMessageResponse {
  bool delivered = 1;
  string message = 2;
}

message ReceiveMessagesRequest {
  string username = 1;
}

message ChatMessageResponse {
  string sender = 1;
  string message = 2;
}

