# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timesystem.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'timesystem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10timesystem.proto\x12\ntimesystem\"D\n\x0eMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"5\n\x0fMessageResponse\x12\x11\n\tdelivered\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"A\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"H\n\x12SendMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"9\n\x13SendMessageResponse\x12\x11\n\tdelivered\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x16ReceiveMessagesRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"6\n\x13\x43hatMessageResponse\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb8\x01\n\x14\x43ommunicationService\x12\x46\n\x0bSendMessage\x12\x1a.timesystem.MessageRequest\x1a\x1b.timesystem.MessageResponse\x12X\n\x0fReceiveMessages\x12\".timesystem.ReceiveMessagesRequest\x1a\x1f.timesystem.ChatMessageResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timesystem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=32
  _globals['_MESSAGEREQUEST']._serialized_end=100
  _globals['_MESSAGERESPONSE']._serialized_start=102
  _globals['_MESSAGERESPONSE']._serialized_end=155
  _globals['_CHATMESSAGE']._serialized_start=157
  _globals['_CHATMESSAGE']._serialized_end=222
  _globals['_SENDMESSAGEREQUEST']._serialized_start=224
  _globals['_SENDMESSAGEREQUEST']._serialized_end=296
  _globals['_SENDMESSAGERESPONSE']._serialized_start=298
  _globals['_SENDMESSAGERESPONSE']._serialized_end=355
  _globals['_RECEIVEMESSAGESREQUEST']._serialized_start=357
  _globals['_RECEIVEMESSAGESREQUEST']._serialized_end=399
  _globals['_CHATMESSAGERESPONSE']._serialized_start=401
  _globals['_CHATMESSAGERESPONSE']._serialized_end=455
  _globals['_COMMUNICATIONSERVICE']._serialized_start=458
  _globals['_COMMUNICATIONSERVICE']._serialized_end=642
# @@protoc_insertion_point(module_scope)
