# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import timesystem_pb2 as timesystem__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in timesystem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommunicationServiceStub(object):
    """all the RPCs for the messaging app are defined under ChatService.

    these are all the different things that the app needs to be able to do:
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/timesystem.CommunicationService/SendMessage',
                request_serializer=timesystem__pb2.MessageRequest.SerializeToString,
                response_deserializer=timesystem__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ReceiveMessages = channel.unary_stream(
                '/timesystem.CommunicationService/ReceiveMessages',
                request_serializer=timesystem__pb2.ReceiveMessagesRequest.SerializeToString,
                response_deserializer=timesystem__pb2.ChatMessageResponse.FromString,
                _registered_method=True)


class CommunicationServiceServicer(object):
    """all the RPCs for the messaging app are defined under ChatService.

    these are all the different things that the app needs to be able to do:
    """

    def SendMessage(self, request, context):
        """send a message from one user to another
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request, context):
        """RPC to receive messages as a stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=timesystem__pb2.MessageRequest.FromString,
                    response_serializer=timesystem__pb2.MessageResponse.SerializeToString,
            ),
            'ReceiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=timesystem__pb2.ReceiveMessagesRequest.FromString,
                    response_serializer=timesystem__pb2.ChatMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'timesystem.CommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('timesystem.CommunicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommunicationService(object):
    """all the RPCs for the messaging app are defined under ChatService.

    these are all the different things that the app needs to be able to do:
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/timesystem.CommunicationService/SendMessage',
            timesystem__pb2.MessageRequest.SerializeToString,
            timesystem__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/timesystem.CommunicationService/ReceiveMessages',
            timesystem__pb2.ReceiveMessagesRequest.SerializeToString,
            timesystem__pb2.ChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
